config/routes.rb
Rails.application.routes.draw do
  
  root to: "homes#top"
  devise_for :users
  resources :users
  resources :books, only: [:new, :create, :edit, :update, :index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end
  
  def create
    @book = Book.create(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path(@book.id)
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    @book.update
    redirect_to book_path(@book.id)
  end
  
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to 
  end

private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model:@book, local:true do |f| %>
<label>Title</label>
<%= f.text_field :title %>
<label>Opinion</label>
<%= f.text_field :body %>
<%= f.submit "Update Book" %>
<% end %>

<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>User info</h1>

<table>
  <tr>
    name <%= @user.name %>
  </tr>
  <tr>
    introduction <%= @user.introduction %> 
  </tr>
</table>

<%= link_to "a", edit_user_path(@user) %>


<h1>New Book</h1>

<%= form_with model:@book, local:true do |f| %>
<label>Title</label>
<%= f.text_field :title %>
<label>Opinion</label>
<%= f.text_field :body %>
<%= f.submit "Create Book" %>
<% end %>


<h1>Books</h1>

<table>
  <% @books.each do |book| %>
  <tr>
    <th>Title</th>
    <th>Opinion</th>
  </tr>
  <tr>
    <td>
      <a><%= book.title %></a>
    </td>
    <td>
      <%= book.body %>
    </td>
  </tr>
  <% end %>
</table>

app/views/books/show.html.erb
<h1> Book detail</h1>

<table>
  <tr>
    <td>
      <a href="/"> <%= @book.title %> </a>
    </td>
    <td>
      <%= @book.body %>
    </td>
  </tr>
</table>

<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Destroy", book_path, method: :delete %>

app/views/homes/top.html.erb
<h1>welcome to <span>Bookers</span>!!</h1><br />
<h3>In <span>Bookers</span>,<br />
<div>you can share and exchange your opinions , inpressions , and emotions</div><br />
<div>about various books!</div>
</h3>

<%= link_to "Log in", new_user_session_path %> <br />
<%= link_to "Sign Up", new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOKERS2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
        <%= link_to "Home", user_path(:id) %>
      </li>
      <li>
        <%= link_to "Users", users_path %>
      </li>
      <li>
        <%= link_to "Books", books_path %>
      </li>
      <li>
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Home", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "About" %>
      </li>
      <li>
        <%= link_to "sign up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "login", new_user_session_path  %>
      </li>
    <% end %>
    <%= yield %>
  </body>
  <footer>
    <div>CopyRight Infratop.inc</div>
  </footer>
</html>